import { type LucideProps } from 'lucide-react'
import type React from 'react'
import {
   Apple,
   Carrot,
   Cherry,
   Banana,
   Grape,
   Citrus,
   Beef,
   Drumstick,
   Fish,
   Ham,
   Egg,
   Milk,
   Wheat,
   Cookie,
   Croissant,
   CakeSlice,
   Cake,
   Package,
   Box,
   Soup,
   Salad,
   UtensilsCrossed,
   ChefHat,
   CookingPot,
   Sandwich,
   Pizza,
   IceCreamCone,
   Coffee,
   CupSoda,
   Wine,
   Beer,
   Martini,
   GlassWater,
   Candy,
   Popcorn,
   Donut,
   Lollipop,
   Snowflake,
   Refrigerator,
   ShoppingCart,
   ShoppingBag,
   Store,
   Receipt,
   Wallet,
   PiggyBank,
   Baby,
   PawPrint,
   SprayCan,
   Trash2,
   Leaf,
   Flame,
   Nut,
   Bean,
} from 'lucide-react'

export type IconComponent = React.ElementType<LucideProps>

// Full library of icons available for the category icon-picker.
// Key = what gets stored on Category.iconKey. Keep keys stable once
// a category has been created with one, since renaming a key here
// would orphan any saved category pointing at the old name.
export const ICON_LIBRARY: Record<string, IconComponent> = {
   apple: Apple,
   carrot: Carrot,
   cherry: Cherry,
   banana: Banana,
   grape: Grape,
   citrus: Citrus,
   beef: Beef,
   drumstick: Drumstick,
   fish: Fish,
   ham: Ham,
   egg: Egg,
   milk: Milk,
   wheat: Wheat,
   cookie: Cookie,
   croissant: Croissant,
   cakeSlice: CakeSlice,
   cake: Cake,
   package: Package,
   box: Box,
   soup: Soup,
   salad: Salad,
   utensilsCrossed: UtensilsCrossed,
   chefHat: ChefHat,
   cookingPot: CookingPot,
   sandwich: Sandwich,
   pizza: Pizza,
   iceCreamCone: IceCreamCone,
   coffee: Coffee,
   cupSoda: CupSoda,
   wine: Wine,
   beer: Beer,
   martini: Martini,
   glassWater: GlassWater,
   candy: Candy,
   popcorn: Popcorn,
   donut: Donut,
   lollipop: Lollipop,
   snowflake: Snowflake,
   refrigerator: Refrigerator,
   shoppingCart: ShoppingCart,
   shoppingBag: ShoppingBag,
   store: Store,
   receipt: Receipt,
   wallet: Wallet,
   piggyBank: PiggyBank,
   baby: Baby,
   pawPrint: PawPrint,
   sprayCan: SprayCan,
   trash2: Trash2,
   leaf: Leaf,
   flame: Flame,
   nut: Nut,
   bean: Bean,
}

// Grouped view of the same library, purely for organizing the icon-picker UI.
export const ICON_GROUPS: { label: string; keys: string[] }[] = [
   { label: 'Produce', keys: ['apple', 'carrot', 'cherry', 'banana', 'grape', 'citrus'] },
   { label: 'Meat & Seafood', keys: ['beef', 'drumstick', 'fish', 'ham', 'egg'] },
   { label: 'Dairy & Bakery', keys: ['milk', 'wheat', 'cookie', 'croissant', 'cakeSlice', 'cake'] },
   {
      label: 'Pantry & Cooking',
      keys: [
         'package',
         'box',
         'soup',
         'salad',
         'utensilsCrossed',
         'chefHat',
         'cookingPot',
         'sandwich',
         'pizza',
         'iceCreamCone',
      ],
   },
   { label: 'Beverages', keys: ['coffee', 'cupSoda', 'wine', 'beer', 'martini', 'glassWater'] },
   { label: 'Snacks & Sweets', keys: ['candy', 'popcorn', 'donut', 'lollipop'] },
   { label: 'Frozen & Cold Storage', keys: ['snowflake', 'refrigerator'] },
   {
      label: 'Household & Non-food',
      keys: [
         'shoppingCart',
         'shoppingBag',
         'store',
         'receipt',
         'wallet',
         'piggyBank',
         'baby',
         'pawPrint',
         'sprayCan',
         'trash2',
      ],
   },
   { label: 'Herbs, Spices & Misc', keys: ['leaf', 'flame', 'nut', 'bean'] },
]

// Kept so existing code (e.g. the entry-list cart icon in GroceryView) keeps working unchanged.
export const iconMap = ICON_LIBRARY
